In [11]:
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks
table_recognition = pipeline(Tasks.table_recognition, model='damo/cv_dla34_table-structure-recognition_cycle-centernet')
result = table_recognition('./1.jpg')

2023-10-24 10:49:19,815 - modelscope - INFO - Model revision not specified, use revision: v0.1
2023-10-24 10:49:21,907 - modelscope - INFO - initiate model from C:\Users\97885\.cache\modelscope\hub\damo\cv_dla34_table-structure-recognition_cycle-centernet
2023-10-24 10:49:21,908 - modelscope - INFO - initiate model from location C:\Users\97885\.cache\modelscope\hub\damo\cv_dla34_table-structure-recognition_cycle-centernet.
2023-10-24 10:49:21,918 - modelscope - WARNING - No preprocessor field found in cfg.
2023-10-24 10:49:21,921 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2023-10-24 10:49:21,921 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': 'C:\\Users\\97885\\.cache\\modelscope\\hub\\damo\\cv_dla34_table-structure-recognition_cycle-centernet'}. trying to build by task and model information.
2023-10-24 10:49:21,922 - modelscope - WARNING - Find ta

In [12]:
a=result['polygons']

In [24]:
a=result['polygons']

b = []
for i in range(len(a)):
    temp = []
    temp.append([int(a[i][0]), int(a[i][1])])
    temp.append([int(a[i][6]), int(a[i][7])])
    temp.append([int(a[i][4]), int(a[i][5])])
    temp.append([int(a[i][2]), int(a[i][3])])
    b.append(temp)

In [25]:
import numpy as np
b= np.array(b)

In [28]:
print(b)

[[[ 29 833]
  [187 834]
  [186 904]
  [ 29 905]]

 [[187 715]
  [317 715]
  [317 833]
  [187 834]]

 [[218 332]
  [408 333]
  [407 380]
  [218 380]]

 [[317 715]
  [425 716]
  [425 834]
  [317 833]]

 [[425 834]
  [662 833]
  [662 904]
  [425 904]]

 [[218 380]
  [407 380]
  [408 428]
  [219 428]]

 [[425 716]
  [494 715]
  [494 833]
  [425 834]]

 [[ 29 380]
  [218 380]
  [219 428]
  [ 29 427]]

 [[ 29 332]
  [218 332]
  [218 380]
  [ 29 380]]

 [[ 29 119]
  [408 119]
  [408 214]
  [ 29 214]]

 [[218 286]
  [408 286]
  [408 333]
  [218 332]]

 [[ 29  50]
  [408  49]
  [408 119]
  [ 29 119]]

 [[ 29 905]
  [186 904]
  [186 951]
  [ 29 951]]

 [[ 29 715]
  [187 715]
  [187 834]
  [ 29 833]]

 [[425 904]
  [662 904]
  [662 951]
  [425 951]]

 [[ 29 286]
  [218 286]
  [218 332]
  [ 29 332]]

 [[494 715]
  [571 715]
  [571 833]
  [494 833]]

 [[186 904]
  [425 904]
  [425 951]
  [186 951]]

 [[187 834]
  [425 834]
  [425 904]
  [186 904]]

 [[ 29 214]
  [408 214]
  [408 286]
  [ 29 286]]

